project:
  title: "Health and Income Research Project"
  output-dir: _products
  execute-dir: project
  pre-render: 
    - utils/check_packages.R      # install required packages
    - utils/remove_artifacts.ts   # remove previously constructed files
  render:
    # if analysis is split into multiple docs, add them here
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/
    - "!bibliography/"

author:
  - name: Jack Aqui
    orcid: 0000-0001-7237-8131
    email: jaqui@uoregon.edu
    url: https://github.com/Jack-Aqui
    attributes:
      corresponding: true
    affiliations:
      - id: uo
        name: University of Oregon
        department: Data Science Student
        address: 760 E 13th Ave
        city: Eugene
        region: OR
        country: USA
        postal-code: 97401
  
execute: 
  freeze: false
  
editor: source



